version: '3.8'
services:
  mongodb:
    image: mongo:8.0.11
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: timeline
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
